4989-Account_Overview_Edit: Edit account details form.
3scale/porta pull request #1950
Opened 2020-06-05 11:25 UTC by dfennessy

**What this PR does / why we need it**:

> Lists UI Strings for Account settings > Overview > Edit account details

**Which issue(s) this PR fixes** 

> `fixes #<4989>`

**Verification steps** 

> None

**Special notes for your reviewer**:

- UI Strings Jira: [THREESCALE-4989](https://issues.redhat.com/browse/THREESCALE-4989)
- Most of the strings contain text similar to the mockup.
- For strings different to the mockup, you will see this tag: [PROPOSED]

2020-06-09 11:21 UTC, dfennessy commented
I removed the strings for default values. How do we represent the placeholder strings? @porueesq

2020-06-09 15:37 UTC, porueesq commented on portafly/src/i18n/locales/en/account_settings/overview/edit_account_details.yml
> +organization_name_validation: {{organization_name_validation}} cannot be blank. Please add your {{organization_name_validation}}.
```suggestion
organization_name_validation: "<i>Organization name</i> cannot be blank. Please add your organization name."
```

2020-06-09 16:23 UTC, porueesq commented on portafly/src/i18n/locales/en/account_settings/overview/edit_account_details.yml
> +organization_name_validation: {{organization_name_validation}} cannot be blank. Please add your {{organization_name_validation}}.
Let's use:
* Italics when referring to field names > _Organization name_ cannot be blank.
* Bold letters when referring to buttons or actions > Choose an item to enable the **Delete** button.
* Italic bold when referring to user names. > Hello **_John_**, You have 5 new messages.

WDYT @dfennessy @cntlsn

2020-06-09 16:48 UTC, porueesq commented on portafly/src/i18n/locales/en/account_settings/overview/edit_account_details.yml
> +time_zone_selectlist_label: Time zone
```suggestion
time_zone_selectlist: Time zone
```

2020-06-09 16:48 UTC, porueesq commented on portafly/src/i18n/locales/en/account_settings/overview/edit_account_details.yml
> +time_zone_selectlist_label_description: Label for the field that holds the time zone of the organization from the select list.
```suggestion
time_zone_selectlist_description: Label for the field that holds the time zone of the organization from the select list.
```

2020-06-09 16:50 UTC, porueesq commented on portafly/src/i18n/locales/en/account_settings/overview/edit_account_details.yml
> +country_selectlist_label: Country
```suggestion
country_selectlist: Country
```

2020-06-09 16:50 UTC, porueesq commented on portafly/src/i18n/locales/en/account_settings/overview/edit_account_details.yml
> +country_selectlist_label_description: Label for the field that holds the name of the organization's country from the select list.
```suggestion
country_selectlist_description: Label for the field that holds the name of the organization's country from the select list.
```

2020-06-09 16:54 UTC, porueesq commented
@dfennessy Some suggestions, and questions for your consideration. See that I've suggested removing the `_label` from some elements, like `selectlist`, for the purpose of simplification.

2020-09-07 14:48 UTC, josemigallas requested changes

2020-09-07 14:48 UTC, josemigallas commented on portafly/src/i18n/locales/en/account_settings/overview/edit_account_details.yml
> +organization_name_validation: {{organization_name_validation}} cannot be blank. Please add your {{organization_name_validation}}.
This phrase has to be between quotes.

2020-09-09 08:05 UTC, josemigallas approved these changes

2020-09-10 08:01 UTC, cntlsn approved these changes

2020-09-10 08:01 UTC, merged