Make it clear for users that system name gets a suffix
3scale/porta pull request #2213
Opened 2020-10-15 08:26 UTC by josemigallas

**What this PR does / why we need it**:
Creates a custom `backend_api_system_name_input` (formtastic) that inserts the necessary UI components. It's a React component and uses PF-React so it doesn't mess (too much) with our styles.

**Which issue(s) this PR fixes** 
[THREESCALE-4761: 
Make it clear for users that the system name of a backend will get a suffix they don't control](https://issues.redhat.com/browse/THREESCALE-4761)

**Verification steps** 
* Go to "new backend" page
* Verify the suffix and the popover are there

2021-02-25 13:52 UTC, hallelujah commented
Sorry, it seems your work did not get enough attention to us.
Thank you for making this project better.

We are going to close it as it was stale for too long.

2021-08-04 08:40 UTC, hallelujah requested changes

2021-08-04 08:40 UTC, hallelujah commented on app/lib/three_scale/semantic_form_builder.rb
> +      input << template.content_tag(:p, '.1234')
??

2021-08-04 08:40 UTC, hallelujah commented on app/lib/three_scale/semantic_form_builder.rb
> +    def backend_api_system_name
I do not think we should use that for just one form.
You can do exactly the same in the html instead of hooking to Formtastic

2021-08-18 06:48 UTC, josemigallas commented
Closing until [THREESCALE-4761](https://issues.redhat.com/browse/THREESCALE-4761) goes back to To Develop.

2021-08-18 06:48 UTC, josemigallas commented
Closing until [THREESCALE-4761](https://issues.redhat.com/browse/THREESCALE-4761) goes back to To Develop.

2021-08-18 08:10 UTC, josemigallas commented
Back to develpment

2021-08-18 08:26 UTC, josemigallas commented on app/lib/three_scale/semantic_form_builder.rb
> +      input << template.content_tag(:p, '.1234')
It's only a draft

2021-08-18 15:46 UTC, thomasmaas approved these changes

2021-08-20 08:38 UTC, cntlsn approved these changes

2021-08-20 08:43 UTC, merged