Member users with rights for specific services should see accounts on…
3scale/porta pull request #2233
Opened 2020-10-28 05:07 UTC by HemaHG

…ly subscribed to that services

Signed-off-by: HemaHG <hhg@redhat.com>

**What this PR does / why we need it**:

> Replace this with a quick explanation of what's included here. 

**Which issue(s) this PR fixes** 

> Replace this comment with references to related issues. This will ensure the issue(s) are closed automatically when the PR gets merged.
> e.g. `fixes #<issue number>(, fixes #<issue_number>, ...)`

**Verification steps** 

> Replace this with a list of necessary steps to verify the PR meets your expectations.
> e.g. `1. Go to Admin Portal, make sure that ...`

**Special notes for your reviewer**:

2020-10-29 13:02 UTC, guicassolato commented on test/integration/buyers/accounts_controller_test.rb
> +    end
I'd try something like this out:

```suggestion
    test "check if user with access to specific service can see accounts particular to that service" do
      buyer_without_applications = @provider.buyers.first

      accessible_service = FactoryBot.create(:service, account: @provider)
      accessible_buyer = FactoryBot.create(:buyer_account, provider_account: @provider)
      accessible_app_plan = FactoryBot.create(:application_plan, issuer: accessible_service)
      accessible_app = FactoryBot.create(:cinstance, user_account: accessible_buyer, plan: accessible_app_plan, name: 'accessbile app')

      forbidden_service = FactoryBot.create(:service, account: @provider)
      forbidden_buyer = FactoryBot.create(:buyer_account, provider_account: @provider)
      forbidden_app_plan = FactoryBot.create(:application_plan, issuer: forbidden_service)
      forbidden_app = FactoryBot.create(:cinstance, user_account: forbidden_buyer, plan: forbidden_app_plan, name: 'forbidden app')

      # member users with restricted access to services should see accounts subscribed to the service
      member = FactoryBot.create(:member, account: @provider, member_permission_ids: [:partners])
      member.member_permission_service_ids = [accessible_service.id]
      member.activate!

      logout! && login!(@provider, user: member)

      get admin_buyers_accounts_path
      assert_equal 2, assigns(:accounts).size
      assert_includes assigns(:accounts), accessible_buyer
      assert_includes assigns(:accounts), buyer_without_applications
      assert_not_includes assigns(:accounts), forbidden_buyer
    end
  end
```

2020-10-29 13:02 UTC, guicassolato commented on app/models/user.rb
> +    accessible_cinstances.select(:user_account_id)).or(buyer_accounts_without_applications)
```suggestion
    buyer_accounts.where(id: accessible_cinstances.select(:user_account_id)).or(buyer_accounts_without_applications)
```

2020-10-30 13:51 UTC, guicassolato commented on test/integration/buyers/accounts_controller_test.rb
> +      buyer = FactoryBot.create(:simple_buyer, provider_account: provider)
It looks like we are not using this buyer in the test.

2020-10-30 13:53 UTC, guicassolato commented on test/integration/buyers/accounts_controller_test.rb
> +      user.member_permission_service_ids = [accessible_service.id, another_service.id]
This is not "all services". I'd skip this line for this test case.

2020-10-30 13:53 UTC, guicassolato commented on test/integration/buyers/accounts_controller_test.rb
> +      buyer = FactoryBot.create(:simple_buyer, provider_account: provider)
Same as https://github.com/3scale/porta/pull/2233/files#r515111751

2020-10-30 13:55 UTC, guicassolato commented on test/integration/buyers/accounts_controller_test.rb
> +      assert_includes assigns(:accounts), accessible_buyer2
```suggestion
      assert_same_elements @provider.buyers, assigns(:accounts)
```

2020-10-30 13:55 UTC, guicassolato commented on test/integration/buyers/accounts_controller_test.rb
> +
```suggestion
```

Considering https://github.com/3scale/porta/pull/2233/files#r515114897

2020-11-02 10:05 UTC, guicassolato approved these changes
LGTM. Nice work and thank you!

2020-11-03 13:49 UTC, Martouta requested changes
I have some proposals/comments to improve this, but I do not have time to test it and explain it properly now. I will try tonight or tomorrow morning :+1:

2020-11-04 13:32 UTC, thomasmaas submitted a review, later dismissed

2020-11-09 11:20 UTC, HemaHG commented
not a valid approach to display the accounts

2020-11-09 11:20 UTC, closed without merging