fixes Developers can manage keys and Allow developers to regenerate a…
3scale/porta pull request #2238
Opened 2020-11-04 10:23 UTC by avilatusell

**What this PR does / why we need it**:
- Prevents rendering the _Regenerate_ button for the Client Secret in the Developer Portal when developers are not allowed to regenerate the Client Secret. 
- Updates the feature description from _Allow developers to regenerate access keys_ to _Allow developers to regenerate Client Secret_ under _Product > Applications - Settings > Usage Rules_ in the Admin Portal when using OIDC authentication mode. 
- When using _app_id & app_key_ authentication mode the option under _Product > Applications - Settings > Usage Rules_ in the Admin Portal _Allow developers to regenerate access keys_ is no longer shown.

**Which issue(s) this PR fixes** 
Fixes [THREESCALE-6295](https://issues.redhat.com/browse/THREESCALE-6295) and [THREESCALE-6296](https://issues.redhat.com/browse/THREESCALE-6296).

**Verification steps** 
_Product with OIDC authentication mode:_
- Go to the Admin Portal  _Product > Applications - Settings > Usage Rules_.
- Under APPLICATION REQUIREMENTS it should be displayed the option _Allow developers to regenerate Client Secret_.
- Enable _Allow developers to regenerate Client Secret_ and make sure to click at the bottom _Update Service_.
  - Go to the Developer Portal > Applications, check one application subscribed to the Product. The regenerate button under Client Secret should appear in red and when using it the Client Secret is regenerated. 
- Disable _Allow developers to regenerate Client Secret_ and make sure to click at the bottom _Update Service_.
  - Go to the Developer Portal > Applications, check one application subscribed to the Product. The regenerate button under Client Secret shouldn't appear. 

_Product with app_id & app_key authentication mode:_
- Go to  the Admin Portal _Product > Applications - Settings > Usage Rules_.
- Under APPLICATION REQUIREMENTS it should be displayed the option _Developers can manage Keys_ but not the option _Allow developers to regenerate Client Secret_.
- Enable _Developers can manage Keys_  and make sure to click at the bottom _Update Service._
  - Go to the Developer Portal > Applications, check one application subscribed to the Product. You should be able to see the _Application ID_ and _Application Keys_ as well as be able to create/delete new _Application Keys_. 
- Disable _Developers can manage Keys_ and make sure to click at the bottom _Update Service_.
  - Go to the Developer Portal > Applications, check one application subscribed to the Product. You can only see _Application ID_ but not _Application Keys_.

2020-11-18 14:09 UTC, kevprice83 approved these changes
Looks good to me. Maybe add a note in the PR saying: _Refer to original issues for complete description of current behaviour_

2021-02-10 16:30 UTC, guicassolato requested changes
I've tested this locally and it seems all right. It could use some minor enhancements and, more importantly, we should add some UI tests before merging. Maybe somebody from @3scale/system-ux can help.

2021-02-10 16:30 UTC, guicassolato commented on config/locales/en.yml
> +        buyer_key_regenerate_enabled: "Allow developers to regenerate Client Secret"
```suggestion
        buyer_key_regenerate_enabled: "Allow developers to regenerate client secret"
```

2021-02-10 16:30 UTC, guicassolato commented on app/views/api/services/forms/_usage_rules.html.slim
> +  - if @service.backend_version > "2"
```suggestion
  - if @service.oauth?
```

2021-02-10 16:30 UTC, guicassolato commented on app/views/api/services/forms/_usage_rules.html.slim
> +  - if @service.backend_version == "2"
```suggestion
  - if @service.backend_version.v2?
```

2021-02-24 22:24 UTC, kevprice83 commented
thanks for the review @guicassolato @3scale/system-ux if you could point @avilatusell to where the tests for this part of the admin portal are I think we could try to work from there.

2021-02-25 13:53 UTC, hallelujah commented
Sorry, it seems your work did not get enough attention from us.
Thank you for making this project better.

We are going to close it as it was stale for too long.

2021-02-25 13:53 UTC, closed without merging