Remove private_endpoint from Proxy
3scale/porta pull request #2278
Opened 2020-11-26 15:15 UTC by josemigallas

**What this PR does / why we need it**:

Since APIAP is now the default, there's no need for this rolling update

**Which issue(s) this PR fixes** 

TBD

2020-11-26 15:17 UTC, Martouta commented on app/models/proxy.rb
> -    end
we still use this... inside this same class

2020-11-26 15:17 UTC, Martouta commented on app/models/proxy.rb
> -  end
we still use this... inside this same class

2020-11-26 15:18 UTC, Martouta requested changes
we cannot remove the port generator because we use it for the proxy model

2020-11-26 15:19 UTC, Martouta commented on app/models/backend_api.rb
>    alias_attribute :api_backend, :private_endpoint
but now the private_endpoint is removed... so, what about this?

2020-11-27 03:55 UTC, Martouta submitted a review, later dismissed

2020-11-27 03:57 UTC, Martouta commented
U will have to fix the tests tho 👍🏼

2020-12-07 16:34 UTC, Martouta requested changes
TODO:
1. Fix the tests of CircleCI.
2. Extract to other PRs the unrelated stuff to what the title/description of the PR says

2021-02-25 17:36 UTC, hallelujah commented
Sorry, it seems your work did not get enough attention from us.
Thank you for making this project better.

We are going to close it as it was stale for too long.

2021-02-25 17:36 UTC, closed without merging