PF compliant buttons: Account settings
3scale/porta pull request #2387
Opened 2021-03-02 11:42 UTC by damianpm

**What this PR does / why we need it**:

> Replace this with a quick explanation of what's included here. 

**Which issue(s) this PR fixes** 

> Replace this comment with references to related issues. This will ensure the issue(s) are closed automatically when the PR gets merged.
> e.g. `fixes #<issue number>(, fixes #<issue_number>, ...)`

**Verification steps** 

> Replace this with a list of necessary steps to verify the PR meets your expectations.
> e.g. `1. Go to Admin Portal, make sure that ...`

**Special notes for your reviewer**:

2021-03-02 17:58 UTC, hallelujah commented on app/views/provider/admin/account/users/_form.html.erb
> +  <%= form.button 'Update User', button_html: { class: 'pf-c-button pf-m-primary' } %>
Same better using locales

2021-03-02 17:58 UTC, hallelujah commented on app/views/provider/admin/accounts/_form.html.erb
> +    <%= form.button 'Update Account', button_html: { class: 'pf-c-button pf-m-primary' }  %>
Same using locales.

2021-03-02 17:58 UTC, hallelujah commented on app/views/provider/admin/user/notification_preferences/_form.html.slim
> +    = f.button 'Update Notification Preferences', button_html: { class: 'pf-c-button pf-m-primary' }
Same using locales

2021-03-02 17:58 UTC, hallelujah commented on app/views/provider/admin/user/personal_details/edit.html.slim
> +    = form.button 'Update Details', button_html: { class: 'pf-c-button pf-m-primary' }
Locales :)

2021-03-02 17:58 UTC, hallelujah commented on app/views/provider/admin/webhooks/edit.html.slim
> +    = f.button 'Update webhooks settings',  button_html: { class: 'pf-c-button pf-m-primary' }
Locales

2021-03-05 10:47 UTC, josemigallas requested changes
LGTM except for one typo

2021-03-05 10:47 UTC, josemigallas commented on config/locales/en.yml
> +    l abels:
```suggestion
    labels:
```

2021-03-05 10:47 UTC, damianpm commented on config/locales/en.yml
> +    l abels:
Oops

2021-03-05 10:49 UTC, josemigallas approved these changes

2021-03-05 15:46 UTC, merged