[2.11] Move Create Mapping Rule button to header
3scale/porta pull request #2418
Opened 2021-04-19 10:05 UTC by josemigallas

**What this PR does / why we need it**:

- Move create button to main section
- Prepare structure for PF4 re-implementation

Product:
![Screenshot 2021-04-19 at 12 01 23](https://user-images.githubusercontent.com/11672286/115219080-7550ba80-a107-11eb-8536-fc83f8b33f40.png)

Backend API:
![Screenshot 2021-04-19 at 12 01 28](https://user-images.githubusercontent.com/11672286/115219114-7da8f580-a107-11eb-84ea-d92b98ee5128.png)

**Which issue(s) this PR fixes** 

[THREESCALE-6874 Improve UI for creating a Product Mapping rule > THREESCALE-6954 Implement Create button with PF4](https://issues.redhat.com/browse/THREESCALE-6954)

2021-04-19 10:12 UTC, cntlsn submitted a review, later dismissed
lgtm, thank you!

2021-04-19 11:53 UTC, thomasmaas submitted a review, later dismissed

2021-04-19 12:27 UTC, damianpm requested changes
LGTM, but there are tests failing, can you check please?

2021-04-23 07:59 UTC, damianpm approved these changes

2021-04-23 15:17 UTC, merged