Fields definition API
3scale/porta pull request #2480
Opened 2021-06-09 15:05 UTC by jsmadis

**What this PR does / why we need it**:

This PR adds fields definition to the admin API.

**Which issue(s) this PR fixes** 

https://issues.redhat.com/browse/THREESCALE-4082

2021-06-25 08:52 UTC, jsmadis commented
FYI this PR exposes an old bug in the fields definition (https://issues.redhat.com/browse/THREESCALE-7189). The bug will be fixed in the separate PR

2021-07-01 16:05 UTC, josemigallas commented on config/routes.rb
> +      resources :fields_definitions, :controller => 'fields_definitions', :except => [:new, :edit]
```suggestion
      resources :fields_definitions, controller: 'fields_definitions', except: %i[new edit]
```

2021-07-01 16:10 UTC, josemigallas requested changes
The requested change is because of the check integrity settings in the webpack config

2021-07-01 16:10 UTC, josemigallas commented on config/webpacker.yml
> +  check_yarn_integrity: false
🚨 
```suggestion
```

2021-07-01 16:10 UTC, josemigallas commented on spec/acceptance/api/fields_definition_spec.rb
> +require 'rails_helper'
```suggestion
#frozen_string_literal: true

require 'rails_helper'
```

2021-07-01 16:10 UTC, josemigallas commented on spec/acceptance/api/fields_definition_spec.rb
> +                                     choices: %w[Orange Apple Banana]) }
Unimportant, but I think this way is more consistent with the ~rest~ majority of the codebase:
```suggestion
  let(:resource) { FactoryBot.create(:fields_definition, account: provider,
                                                         target: 'Account',
                                                         name: 'stuff',
                                                         choices: %w[Orange Apple Banana]) }
```

2021-07-12 07:55 UTC, josemigallas reviewed
Looking at the spec file, should we also add cases for `show` and `destroy`?

2021-07-12 12:44 UTC, hallelujah approved these changes
:rocket:

2021-07-12 14:11 UTC, jsmadis commented
I will add some tests, @josemigallas  is right :)

2021-07-12 15:56 UTC, jsmadis commented
Rebased with the actual master because it contains the fix for the failing cucumber tests

2021-07-13 08:39 UTC, josemigallas approved these changes

2021-07-13 10:00 UTC, merged