letter_opener made easy
3scale/porta pull request #2485
Opened 2021-06-14 20:47 UTC by akostadinov

**What this PR does / why we need it**:

Makes easy to enable `email_opener` by a simple environment variable at runtime.

```
$ LETTER_OPENER=1 bundle exec sidekiq ...
```

**Which issue(s) this PR fixes** 

No issue.

**Verification steps** 

- export LETTER_OPENER=1
- bundle exec sidekiq ...
- in Porta web UI invire a user
- a browser tab should open with email content present

**Special notes for your reviewer**:

2021-06-14 20:52 UTC, akostadinov commented on config/environments/development.rb
> +    config.action_mailer.delivery_method = :smtp
This is to allow using actual SMTP delivery when SMTP configuration is present.

2021-06-14 22:13 UTC, hallelujah commented
Nice PR, can you fix Code Climate? also and trigger the `javascript_tests` and `mysql_build` checks?

2021-06-14 22:15 UTC, hallelujah requested changes
Remark, in your comment you mentionned sidekiq but some emails are sent in the request so technically `rails server` is also impacted

2021-06-15 07:12 UTC, akostadinov commented
hmm, I was thinking it's gonna complain if I use `var = case ...` but it got the other way around. I should have checked locally.

2021-06-15 10:14 UTC, hallelujah approved these changes

2021-06-15 14:33 UTC, merged