[Threescale-7189] Fixes position of the fields definitions
3scale/porta pull request #2501
Opened 2021-06-28 15:18 UTC by jsmadis

**What this PR does / why we need it**:

The introduction of the API (https://github.com/3scale/porta/pull/2480) for the field's definition pointed out an old bug with positions.
The fields definition uses the position column for the order of the fields. The `act_as_list` library doesn't know how to handle the list where the position is based on the `target` field, so it tries to update the position for every field, and it breaks the positions.

This PR introduces a fix for it. It overrides the update and corrects the positions of the fields. 

**Which issue(s) this PR fixes** 

https://issues.redhat.com/browse/THREESCALE-7189

**Verification steps** 

The position is not visible yet, but https://github.com/3scale/porta/pull/2480 introduces the API, which will expose the position.

**Special notes for your reviewer**:

Personally, I am not sure if this works safely (updating other entities in the update method). I am afraid that concurrent requests for updates might result in misconfiguration.

2021-06-28 15:52 UTC, hallelujah requested changes
Isn't using `:target` in the `scope` not working?

2021-06-28 15:52 UTC, hallelujah commented on app/models/fields_definition.rb
> +      fields_definitions = account.fields_definitions.select {|field| field.target == self.target}.sort_by { |field| field.pos  }
Why not using:

```ruby
acts_as_list scope: [:account_id, :target], column: :pos
```

2021-07-01 15:40 UTC, josemigallas commented on test/unit/fields_definition_test.rb
> +    should 'change position when updated' do
```suggestion

    should 'change position when updated' do
```

2021-07-01 15:40 UTC, josemigallas commented on test/unit/fields_definition_test.rb
> +    should 'return correct positions' do
```suggestion

    should 'return correct positions' do
```

2021-07-01 15:45 UTC, josemigallas commented on test/unit/fields_definition_test.rb
> +      assert @read_only.pos == @required.pos  - 1
```suggestion
      assert_equal @hidden.pos, @read_only.pos - 1
      assert_equal @read_only.pos, @required.pos  - 1
```

2021-07-01 15:46 UTC, josemigallas commented on test/unit/fields_definition_test.rb
> +      assert !@required.errors.empty?
```suggestion
      assert_not @required.errors.empty?
```

2021-07-01 15:48 UTC, josemigallas commented on test/unit/fields_definition_test.rb
> +      @acc_target_another = FactoryBot.create(:fields_definition, :account => @provider, :name => "other2", :required => true, target: 'Account')
```suggestion
      @hidden = FactoryBot.create(:fields_definition, account: @provider, name: 'hidden', hidden: true)
      @read_only = FactoryBot.create(:fields_definition, account: @provider, name: 'read_only', read_only: true)
      @required = FactoryBot.create(:fields_definition, account: @provider, name: 'required', required: true)
      @acc_target = FactoryBot.create(:fields_definition, account: @provider, name: 'other', required: true, target: 'Account')
      @acc_target_another = FactoryBot.create(:fields_definition, account: @provider, name: 'other2', required: true, target: 'Account')
```

2021-07-12 12:40 UTC, hallelujah approved these changes

2021-07-12 12:40 UTC, merged