[THREESCALE-7134] Removing ProviderLuaGenerator class
3scale/porta pull request #2513
Opened 2021-07-05 14:25 UTC by HemaHG

**What this PR does / why we need it**:

Removing ProviderLuaGenerator class

**Which issue(s) this PR fixes** 

   part of [THREESCALE-7134](https://issues.redhat.com/browse/THREESCALE-7134)

2021-07-12 12:58 UTC, hallelujah requested changes
Shouldn't you remove first the classes using it and above in the hierarchy?

To my point of view we should remove the ones that are using it first (unless it is also used in more scenarii)
ProviderPackageGenerator looks a good one to remove first.

2021-07-22 10:23 UTC, jsmadis approved these changes

2021-07-22 10:51 UTC, HemaHG commented
Done in PR https://github.com/3scale/porta/pull/2525

2021-07-22 14:24 UTC, akostadinov approved these changes
I see no remaining references to ProviderLuaGenerator. LGTM

2021-07-22 14:56 UTC, hallelujah approved these changes

2021-07-22 14:59 UTC, merged