<!--  Thanks for sending a pull request!  Here are some tips for you: 1. Please remember to ALWAYS open an issue before starting to work on your pull request. Please take the time to validate your intentions for the pull request with the project maintainers before spending the time to work on it, so your time does not go to waste.  2. If this is your first time, please make sure you've gone through the Contribution guide. 3. If the PR is unfinished, add a `[WIP]` at the start of the PR title. You can remove it when it's ready to be reviewed. -->
3scale/porta pull request #2529
Opened 2021-07-15 13:02 UTC by akostadinov

**What this PR does / why we need it**:

> Replace this with a quick explanation of what's included here. 

**Which issue(s) this PR fixes** 

> Replace this comment with references to related issues. This will ensure the issue(s) are closed automatically when the PR gets merged.
> e.g. `fixes #<issue number>(, fixes #<issue_number>, ...)`

**Verification steps** 

> Replace this with a list of necessary steps to verify the PR meets your expectations.
> e.g. `1. Go to Admin Portal, make sure that ...`

**Special notes for your reviewer**:

2021-07-19 08:59 UTC, akostadinov commented on .gitignore
> -.tool-versions
It is a redundant entry

2021-07-19 13:06 UTC, akostadinov commented on .gitignore
> +!/tmp/metrics
wait, this was not about tests or IDEA, I forgot and spent far too long to figure that out now :/

In fact there is an error in server logs (and IIRC sidekiq in certain conditions that I didn't reproduce).

```
D, [2021-07-19T15:49:38.614887 #575377] DEBUG -- : error No such file or directory @ rb_sysopen - /home/avalon/ws/repos/porta/tmp/metrics/histogram_575377-0.db backtrace /home/avalon/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/prometheus-client-mmap-0.11.0/lib/prometheus/client/helper/file_locker.rb:13:in `initialize'
/home/avalon/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/prometheus-client-mmap-0.11.0/lib/prometheus/client/helper/file_locker.rb:13:in `open'
/home/avalon/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/prometheus-client-mmap-0.11.0/lib/prometheus/client/helper/file_locker.rb:13:in `block in lock_to_process'
/home/avalon/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/prometheus-client-mmap-0.11.0/lib/prometheus/client/helper/file_locker.rb:9:in `synchronize'
/home/avalon/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/prometheus-client-mmap-0.11.0/lib/prometheus/client/helper/file_locker.rb:9:in `lock_to_process'
/home/avalon/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/prometheus-client-mmap-0.11.0/lib/prometheus/client/helper/mmaped_file.rb:45:in `block in ensure_exclusive_file'
...
```

2021-07-19 14:52 UTC, hallelujah commented on .gitignore
> +!/tmp/metrics
Ah but how did you get this? I do not set `prometheus_multiproc_dir` environment variable and I have no issue

2021-07-19 15:50 UTC, akostadinov commented on .gitignore
> +!/tmp/metrics
Thank you for pointing that out. I didn't notice setup scripts set this directory and it is not set by porta OOB. I removed this commit and will consider a proper way to fix setup scripts.

2021-07-21 07:56 UTC, hallelujah requested changes

2021-07-21 07:56 UTC, hallelujah commented on test/test_helper.rb
> +unless ENV['RM_INFO']
```suggestion
# this environment variable is set by Intellij IDEA which is not compatible with those reporters
unless ENV['RM_INFO']
```

2021-07-22 12:26 UTC, hallelujah approved these changes

2021-07-22 12:26 UTC, merged