Application's Change Plan dropdown
3scale/porta pull request #2555
Opened 2021-07-29 12:04 UTC by josemigallas

**What this PR does / why we need it**:

Re implement the change plan card with React and PF4.

https://user-images.githubusercontent.com/11672286/127488452-d00a7cbf-7c13-40a8-a72e-200416e0d4ff.mp4

**Which issue(s) this PR fixes** 

[THREESCALE-6871: Improve UI for changing Application plan for existing Application](https://issues.redhat.com/browse/THREESCALE-6871)

**Verification steps** 

Audience > Applications > select 1 application > change the plan

**Special notes for your reviewer**:
The final design differs a little bit from the mockup.

2021-07-29 12:46 UTC, hallelujah approved these changes

2021-08-02 15:25 UTC, cntlsn requested changes
@josemigallas this looks great!
just one request: when cleaning up the input field, the menu item gets back to becoming clickable but its appearance is still like it's disabled. can we also revert its appearance so that it is more intuitive for the user?

2021-08-04 08:44 UTC, hallelujah approved these changes

2021-08-04 08:45 UTC, guicassolato approved these changes

2021-08-04 14:34 UTC, damianpm approved these changes
LGTM

2021-08-05 10:46 UTC, hallelujah submitted a review, later dismissed

2021-08-16 12:21 UTC, cntlsn approved these changes
🎉

2021-08-17 10:53 UTC, merged