ActiveDocs: Do not inject autocomplete fields in plain/text responses
3scale/porta pull request #2568
Opened 2021-08-09 16:00 UTC by damianpm

**What this PR does / why we need it**:

> Replace this with a quick explanation of what's included here. 

**Which issue(s) this PR fixes** 

> Replace this comment with references to related issues. This will ensure the issue(s) are closed automatically when the PR gets merged.
> e.g. `fixes #<issue number>(, fixes #<issue_number>, ...)`

**Verification steps** 

> Replace this with a list of necessary steps to verify the PR meets your expectations.
> e.g. `1. Go to Admin Portal, make sure that ...`

**Special notes for your reviewer**:

2021-08-10 13:00 UTC, josemigallas requested changes

2021-08-10 13:00 UTC, josemigallas commented on app/javascript/packs/OAS3Autocomplete.js
>  const injectServerToResponseBody = (responseBody: ResponseBody, serviceEndpoint: string): ResponseBody => {
```suggestion
const injectServerToResponseBody = (responseBody: ResponseBody | string, serviceEndpoint: string): ResponseBody => {
```

2021-08-10 15:00 UTC, damianpm commented on app/javascript/packs/OAS3Autocomplete.js
> -const isSpecFetched = (response: SwaggerResponse): boolean => !!response.body.method
I just realized this method is totally useless, don't remember why it was included

2021-08-10 15:20 UTC, josemigallas commented on app/javascript/packs/OAS3Autocomplete.js
> +  const res = (responseBody.paths && accountData) ? {
```suggestion
  const res = (typeof responseBody !== 'string' && responseBody.paths && accountData) ? {
```
Alternatively add it to guard in line 63
```
if (typeof responseBody === 'string' || !responseBody.paths || !accountData) {
  return responseBody
}
```

2021-08-11 08:24 UTC, josemigallas approved these changes

2021-08-11 08:53 UTC, merged