Fix Application plans select
3scale/porta pull request #2702
Opened 2021-11-04 12:33 UTC by josemigallas

**What this PR does / why we need it**:

Removes `buyerCanSelectPlan` parameter, which in fact means _developer can select plan_ and it shouldn't affect the New Application page.

**Which issue(s) this PR fixes** 

[THREESCALE-7834: admin can't create application when developer is not allowed to pick a plan](https://issues.redhat.com/browse/THREESCALE-7834)

**Verification steps** 

See JIRA

2021-11-04 14:03 UTC, akostadinov approved these changes
On ruby side I only see some data removed from presenter so looks good. As long as page looks good, the js parts also seem ok to me.

2021-11-04 14:10 UTC, hallelujah approved these changes

2021-11-04 14:10 UTC, damianpm approved these changes

2021-11-04 14:29 UTC, damianpm requested changes
LGTM js side, but cukes failing

2021-11-05 10:29 UTC, damianpm approved these changes

2021-11-05 10:31 UTC, hallelujah approved these changes

2021-11-05 10:31 UTC, merged