[Params] Fixes devel portal contracts/service_plans/application controllers
3scale/porta pull request #2767
Opened 2021-11-24 10:32 UTC by jsmadis

**What this PR does / why we need it**:
Fixes usage of params in the controller in the:

```
./lib/developer_portal/app/controllers/developer_portal/admin/contracts_controller.rb
./lib/developer_portal/app/controllers/developer_portal/admin/contracts/service_plans_controller.rb
./lib/developer_portal/app/controllers/developer_portal/admin/applications_controller.rb
```

2021-11-29 09:07 UTC, akostadinov requested changes
Looks great, just 2 nitpicks.

2021-11-29 09:07 UTC, akostadinov commented on lib/developer_portal/app/controllers/developer_portal/admin/applications_controller.rb
> +  def local_params
Maybe name it `app_params` or something? Unless this `local_params` name is some convention I'm unaware of, in which case it is fine with me.

2021-11-29 09:07 UTC, akostadinov commented on lib/developer_portal/app/controllers/developer_portal/admin/applications_controller.rb
> +    params.permit(%i[plan_id service_id page]).to_h
```suggestion
    params.permit(%i[plan_id service_id page])
```

In file parameters seem to be used as parameters, not hash. So perhaps remove `to_h`.

2021-12-06 12:49 UTC, jsmadis commented on lib/developer_portal/app/controllers/developer_portal/admin/applications_controller.rb
> +                 elsif (service_id = local_params[:service_id])
You are right, it's not. Those PR's were made when I had insufficient knowledge in the problematic area and are made to point stuff like this. Thanks for the comment.

2021-12-07 12:32 UTC, jsmadis commented
After further investigation, I found out that those files don't need to be changed.

2021-12-07 12:32 UTC, closed without merging