[params] Fixes providers base controller
3scale/porta pull request #2803
Opened 2021-11-30 09:05 UTC by nidhi-soni1104

**What this PR does / why we need it:**
Fixes usage of params in the base controller

2021-12-02 14:08 UTC, hallelujah requested changes

2021-12-02 14:08 UTC, hallelujah commented on app/controllers/master/providers/base_controller.rb
> +        @provider = Provider.find(params.permit!.to_h[:provider_id])
```suggestion
        @provider = Provider.find(params.require(:provider_id))
```

2021-12-14 10:30 UTC, hallelujah approved these changes

2021-12-14 13:47 UTC, josemigallas approved these changes

2021-12-15 07:46 UTC, merged