[params] Fixes admin account controllers
3scale/porta pull request #2834
Opened 2021-12-08 18:29 UTC by nidhi-soni1104

**What this PR does / why we need it:**
Fixes usage of params in the admin account controllers

2021-12-09 14:10 UTC, hallelujah requested changes

2021-12-09 14:10 UTC, hallelujah commented on app/controllers/provider/admin/account/payment_gateways/braintree_blue_controller.rb
> +    if current_account.update_attributes params.premit(:account)[:account]
```suggestion
    if current_account.update_attributes params.permit(:account)[:account]
```

2021-12-09 18:49 UTC, nidhi-soni1104 commented
@hallelujah fixed

2021-12-13 14:43 UTC, hallelujah approved these changes

2021-12-13 14:43 UTC, merged