THREESCALE-8140 Prevent emails from being sent without subject and/or body for applications
3scale/porta pull request #2934
Opened 2022-03-10 11:10 UTC by nidhi-soni1104

**What this PR does / why we need it:**

When sending emails from the bulk operations emails can be sent if body and subject is empty
make those field required

Which issue(s) this PR fixes

Main task : https://issues.redhat.com/browse/THREESCALE-8009

SubTask: https://issues.redhat.com/browse/THREESCALE-8140

2022-03-31 08:19 UTC, josemigallas approved these changes

2022-03-31 09:51 UTC, akostadinov requested changes
Looks good but indentation is screwed.

2022-03-31 16:37 UTC, akostadinov commented
Please watch carefully. Another style of indentation is only used in `Background`, I don't know why. But in scenarios normal indentation is used. Also the added lines do not follow the indentation style of `Background` either.

2022-04-04 07:09 UTC, josemigallas commented
```gherkin
Feature: indentation is irrelevant

    Background:
      Given ...

    Scenario:
      Then ...
      And here is a multiline string:
        '''
        I can be here or 1 to the left
        '''
```

2022-04-04 11:10 UTC, akostadinov approved these changes

2022-04-04 11:10 UTC, akostadinov commented
@josemigallas , where did you get this from? 4 spaces indentation for scenarios and background?!

2022-04-04 11:25 UTC, nidhi-soni1104 commented
@josemigallas Can I merge this PR?

2022-04-05 07:01 UTC, josemigallas commented
> @josemigallas , where did you get this from? 4 spaces indentation for scenarios and background?!

I forgot the `Rule` 😅. It's updated now

2022-04-06 10:24 UTC, merged