hotfix/httpclient_fork
3scale/porta pull request #3127
Opened 2022-12-06 06:36 UTC by gsaslis

**What this PR does / why we need it**:

Updates the fork used for the `httpclient` ruby gem

**Special notes for your reviewer**:

same exact code on both forks - the 3scale one having the benefit that it doesn't depend on an external (nowadays) contributor.

2022-12-06 12:55 UTC, mayorova approved these changes

2022-12-06 13:19 UTC, mayorova requested changes
The `ssl-env-cert` branches in the two repos are not actually equal:
https://github.com/mikz/httpclient/compare/ssl-env-cert...3scale:httpclient:ssl-env-cert

Once Gemfile.lock is regenerated, the code will not be the same.

We need to investigate which one is desired.

2022-12-06 13:39 UTC, gsaslis commented
Great catch @mayorova !! 👏🏼 

I've updated the PR to point to the expected git commit hash

2022-12-06 23:13 UTC, akostadinov approved these changes

2022-12-06 23:15 UTC, akostadinov commented
They used `require_relative` instead of `require` to fix an issue affecting cachito. It is valid change and follows community practices as far as I've investigated earlier.

2022-12-07 06:53 UTC, gsaslis commented
@mayorova I think you need to approve in order for this to be merged. ;)

2022-12-07 08:57 UTC, mayorova approved these changes

2022-12-07 08:58 UTC, merged