🚧 WIP: THREESCALE-9196: Added the quick start for learning about products.
3scale/porta pull request #3252
Opened 2023-03-13 12:58 UTC by dfennessy

**What this PR does / why we need it**: 

> This PR adds the quick start for learning about products.

**Which issue(s) this PR fixes** 

> [THREESCALE-9196](https://issues.redhat.com/browse/THREESCALE-9196)

**Verification steps** 

**Reviewers**

* Eng: @josemigallas / @lvillen 
* Docs: @lcavalle

2023-03-13 13:51 UTC, dfennessy commented
Some questions that need to be considered:

- How do we split the page up between quick starts and the new content. For example documentation and/or the new content as in this PR, which isn't really a "task", but information? Like it's done here: https://console.redhat.com/application-services/learning-resources?
- How/where do we add images? Which folder? An existing folder in the repo or a new folder for these assets?
- Removing the review your work module causes an issue with clicking Next. It looks like it's still picking up the check your work part, so two clicks is requires to finish the task.

2023-03-14 09:15 UTC, lcavalle requested changes

2023-03-14 09:15 UTC, lcavalle commented on app/javascript/src/QuickStarts/templates/learnAboutProducts.yaml
> +    In this quick start, you will learn about application plans. To learn more, see the [3scale documentation](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.13/html/ge
Little correction in the text. URL is invalid.

```suggestion
    In this quick start, you will learn about products. To learn more, see the [3scale documentation](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.13/html/getting_started/first-steps-with-threescale_configuring-your-api#creating-products-test-api-calls_configuring-your-api).
```

2023-04-04 15:13 UTC, lvillen commented
> Some questions that need to be considered:

Maybe this can be of help: 


> 1. How do we split the page up between quick starts and the new content. For example documentation and/or the new content as in this PR, which isn't really a "task", but information? Like it's done here: https://console.redhat.com/application-services/learning-resources?

There's not a clear way to do this, but we'll reach PF team and see what can we do about it.

> 2. How/where do we add images? Which folder? An existing folder in the repo or a new folder for these assets?

Let's add a new folder for images at `QuickStarts/templates/images`. We can use images like in any regular Markdown or use an HTML tag like the following example: https://github.com/patternfly/patternfly-quickstarts/blob/720dbd5dc56f65eeac9383b65e05be1c13197e4e/packages/dev/src/quickstarts-data/yaml/template.yaml#L45-L46

> 3. Removing the review your work module causes an issue with clicking Next. It looks like it's still picking up the check your work part, so two clicks is requires to finish the task.



> 4. How do we link to other Quick Start cards? For example the Next option for this links to _[Create an API Product]_

You can use the nextQuickStart markdown tag as you can check in the following example: 
https://github.com/patternfly/patternfly-quickstarts/blob/720dbd5dc56f65eeac9383b65e05be1c13197e4e/packages/dev/src/quickstarts-data/yaml/template.yaml#L136-L137

> 5. Which URL should be used to point to information about Products. Currently I am using this one: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.13/html/getting_started/first-steps-with-threescale_configuring-your-api#creating-products-test-api-calls_configuring-your-api

2023-05-18 16:12 UTC, dfennessy commented
Does anyone know why "Some checks haven’t completed yet" and doesn't complete? Is there something I need to do/fix so that these checks pass?

2023-05-25 11:27 UTC, dfennessy commented
@josemigallas @lcavalle 
Doing some research about how to split up the page as noted in my previous comment in question 1. It looks like that magic possibly happens here: `app/javascript/src/QuickStarts/components/QuickStartContainer.tsx` There is some code for the `QuickStartCatalogPage`, which maybe we can replicate for adding the Documentation and tour-related content?

2023-07-06 13:03 UTC, dfennessy commented
> FAO: @lvillen @josemigallas
> 
> Some questions that need to be considered:
> 
> 1. How do we split the page up between quick starts and the new content. For example documentation and/or the new content as in this PR, which isn't really a "task", but information? Like it's done here: https://console.redhat.com/application-services/learning-resources?
> 2. How/where do we add images? Which folder? An existing folder in the repo or a new folder for these assets?
> 3. Removing the review your work module causes an issue with clicking Next. It looks like it's still picking up the check your work part, so two clicks is requires to finish the task.
> 4. How do we link to other Quick Start cards? For example the Next option for this links to _[Create an API Product]_
> 5. Which URL should be used to point to information about Products. Currently I am using this one: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.13/html/getting_started/first-steps-with-threescale_configuring-your-api#creating-products-test-api-calls_configuring-your-api

FAO: @lvillen @josemigallas

Regarding the below original queries I had. I'm crossing out ones I've taken care of, leaving the ones I'm still working on, and making bold for you guys the ones you'll take care of:

1. **How do we split the page up between quick starts and the new content. For example documentation and/or the new content as in this PR, which isn't really a "task", but information? Like it's done here: https://console.redhat.com/application-services/learning-resources?**
~2. How/where do we add images? Which folder? An existing folder in the repo or a new folder for these assets?~
3. **Removing the review your work module causes an issue with clicking Next. It looks like it's still picking up the check your work part, so two clicks is requires to finish the task.**
4. How do we link to other Quick Start cards? For example the Next option for this links to [Create an API Product]
5. ~Which URL should be used to point to information about Products. Currently I am using this one: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.13/html/getting_started/first-steps-with-threescale_configuring-your-api#creating-products-test-api-calls_configuring-your-api~

2023-07-13 09:38 UTC, dfennessy commented
@lcavalle @josemigallas  

I clicked ready for review. Hopefully that is the correct action. WIP still remains in the title, but that's probably correct, right?

2023-07-28 09:29 UTC, closed without merging

2023-07-28 09:30 UTC, dfennessy commented
Refer to https://github.com/3scale/porta/pull/3489