🚧 Remove toggling services
3scale/porta pull request #3276
Opened 2023-03-23 12:12 UTC by lvillen

**What this PR does / why we need it**:

This PR deletes some old code which doesn't relate on how we work with Products nowadays. 

In the past we had multi-service accounts (see issue[ #5927](https://github.com/3scale/system/issues/5927) on System repo) and the solution we came up with was a toggling system for different services (see System PRs [#5927](https://github.com/3scale/system/issues/5927), [#6264](https://github.com/3scale/system/pull/6271) and [#6366](https://github.com/3scale/system/pull/6366)). 

This is not the case anymore so we can move forward without this code.

2023-03-24 09:38 UTC, mayorova commented on app/views/api/services/show.html.slim
> -- content_for :javascripts do
There is a block at the end of this file that should be removed too:
```
javascript:
  document.addEventListener('DOMContentLoaded', function () {
    serviceInitialize()
  })
```

2023-03-24 09:43 UTC, mayorova requested changes
Just one comment - otherwise looks good

2023-03-27 09:17 UTC, mayorova submitted a review, later dismissed

2023-03-29 09:06 UTC, thalesmiguel approved these changes

2023-03-29 09:41 UTC, josemigallas requested changes
The following files still have traces:
- app/assets/stylesheets/provider/_services.scss (title-toggle, is-closed)
- app/javascript/src/Types/globals.d.ts (serviceInitialize)

2023-03-29 11:03 UTC, josemigallas approved these changes
🥇

2023-03-29 13:04 UTC, merged