Threescale 8748 update product overview header
3scale/porta pull request #3661
Opened 2024-01-08 11:04 UTC by nidhi-soni1104

2024-01-16 11:39 UTC, lvillen requested changes
Though this change is ok, from Melody's comment I understand that the issue's request is changing the sidebar menu link from `Overview` to `Product/backend overview`.

2024-01-16 11:39 UTC, lvillen commented on app/views/api/services/show.html.slim
> +- content_for :page_header_title, 'Product Overview'
```suggestion
- content_for :page_header_title, 'Product overview'
```

2024-01-16 11:41 UTC, nidhi-soni1104 commented
> Though this change is ok, from Melody's comment I understand that the issue's request is changing the sidebar menu link from `Overview` to `Product/backend overview`.

@lvillen Done

2024-01-16 14:40 UTC, nidhi-soni1104 commented
> But we're still missing the other part of the issue. As you can see in the example screenshot below, the Overview button on the sidebar menu should be updated to Product overview (or Backend overview, depending on the context).
> <img alt="Captura de pantalla 2024-01-16 a las 13 38 46" width="322" src="https://private-user-images.githubusercontent.com/72191439/297047489-084c9797-c3aa-4903-a7d7-f9e715ef2e2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDkxMjEsIm5iZiI6MTcwNTQwODgyMSwicGF0aCI6Ii83MjE5MTQzOS8yOTcwNDc0ODktMDg0Yzk3OTctYzNhYS00OTAzLWE3ZDctZjllNzE1ZWYyZTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEyNDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZDYxMWY3MGRmODhiM2E5NzRmZmI1MTZhNzhjOTk1YmYwNzAzYWUwYjcyNTk5MTY0NTYwNTI5N2YzZWZjMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TgVP8g3JKbwO67u6zP8JAVHqmI-YEvDLMiZ8jlKWuQc">

@lvillen I am not sure if sidebar menu should be updated  or not but okay I will update this too

2024-01-17 15:37 UTC, nidhi-soni1104 commented
@lvillen Changes done

2024-01-18 11:25 UTC, lvillen commented
One last thing, could you change the header for `Backend overview` to `Backend Overview` as you've already done in Product?

2024-01-18 13:08 UTC, nidhi-soni1104 commented
> Backend overview

done

![image](https://github.com/3scale/porta/assets/84672731/fdd17d1d-4b57-4a80-aa13-ce3640a0db00)

2024-01-18 15:35 UTC, lvillen approved these changes

2024-01-23 06:05 UTC, merged