Threescale 8747 add description for acc app
3scale/porta pull request #3665
Opened 2024-01-09 10:25 UTC by nidhi-soni1104

What this PR does / why we need it:

No description in [Product_applications_listing] page & [Product_accounts_listing]

Improvement: Add a description for audience/applications and audience/accounts.

Location

    https://red-hat-wat-admin.3scale.net/p/admin/applications
    https://red-hat-wat-admin.3scale.net/buyers/accounts

 Microcopy

    https://docs.google.com/document/d/1igPAmV9g78R3tlm8O3fifgAFNq7hYuitz0_1JpRuj0k/edit#

Which issue(s) this PR fixes
https://issues.redhat.com/browse/THREESCALE-8747

![image](https://github.com/3scale/porta/assets/84672731/55c4f47a-62db-45c9-85e8-30da47d7ef2a)
![image](https://github.com/3scale/porta/assets/84672731/fca14fd7-85d2-4efa-ba38-5b1f16d55880)

2024-01-16 11:51 UTC, josemigallas requested changes
This looks clearly wrong and besides, the "description" feature is already implemented. See apiconfig/services/3/backend_usages for example.

2024-01-16 14:47 UTC, nidhi-soni1104 commented
> This looks clearly wrong and besides, the "description" feature is already implemented. See apiconfig/services/3/backend_usages for example.

okay let me check and do the changes accordingly

2024-01-18 09:06 UTC, nidhi-soni1104 commented
@josemigallas changes done accordingly

![image](https://github.com/3scale/porta/assets/84672731/d999726c-d331-4922-ae3c-0b99aa004b10)
![image](https://github.com/3scale/porta/assets/84672731/a1434e2d-bc1b-49f7-afd1-2125a9abb973)

2024-01-29 08:41 UTC, josemigallas approved these changes

2024-01-29 09:58 UTC, merged