⚰️ Authorize.net is dead: DB migrations
3scale/porta pull request #3703
Opened 2024-02-26 09:10 UTC by josemigallas

[THREESCALE-10819: Remove Account column credit_card_authorize_net_payment_profile_token from DB](https://issues.redhat.com/browse/THREESCALE-10819)

2024-02-28 09:09 UTC, akostadinov commented on db/migrate/20230224151935_remove_authorize_net_c_ctoken_from_account.rb
Also needs to be tested on the stg database to see how long it takes to run. This is probably the biggest table and we absolutely don't want it blocked for long.

2024-02-28 09:23 UTC, jlledom commented on db/migrate/20230224151935_remove_authorize_net_c_ctoken_from_account.rb
On the other hand, running a migration that removes a column directly in production would be funnier. I suggest to do it on Friday.

2024-03-04 08:30 UTC, jlledom requested changes
The column should be removed also from `oracle_schema.rb`

2024-03-20 13:55 UTC, jlledom approved these changes

2024-04-08 12:46 UTC, jlledom commented
Why don't you merge this one?

2024-04-10 15:10 UTC, jlledom requested changes

2024-04-10 15:10 UTC, jlledom commented on db/oracle_schema.rb
The Oracle schema hasn't been properly updated because the column is not removed.

2024-04-10 18:27 UTC, mayorova commented on db/oracle_schema.rb
Good catch

2024-04-11 08:59 UTC, jlledom commented
All tests pass except cucumbers in oracle. Those keep failing but I'd say it's not related to authorize.net.

2024-04-11 09:18 UTC, merged

2024-04-11 09:18 UTC, jlledom approved these changes