THREESCALE-9327 Quick Start content- Main Page Part 2
3scale/porta pull request #3726
Opened 2024-03-18 16:07 UTC by lvillen

**What this PR does / why we need it**:

Now that Quick starts are available, we want to make them more accessible. In order to achieve that, the desing team proposed two different actions:

1. Adding a Quickstarts button to the dashb
![Captura de pantalla 2024-03-18 a las 16 34 23](https://github.com/3scale/porta/assets/72191439/e0887898-9483-4f9e-828f-36f8f3f289ca)
oard. 

2. When users log in for the first time, they should receive a notification informing them that Quickstarts are available and encouraging them to take a tour.
![Captura de pantalla 2024-03-18 a las 16 41 19](https://github.com/3scale/porta/assets/72191439/b35c0166-3c9f-4a89-ad07-7c9d59779d64)

**Which issue(s) this PR fixes** 

[THREESCALE-9327](https://issues.redhat.com/browse/THREESCALE-9327)

**Verification steps** 

1. Go to the dashboard and confirm there is a Quickstarts button.
2. Click the button and confirm you're redirected to `/p/admin/quickstarts`.
3. Create a new provider.
4. Confirm that on login you receive the Quickstarts notification.
5. Confirm that after logout and login again you don't receive the Quickstarts notification.

2024-03-18 16:09 UTC, lvillen commented
@dfennessy @lcavalle currently at the dashboard we have a button with string `Quickstarts` that redirect to Quickstarts page which has a header `Quick starts`. Could you please clarify if we should use `Quickstarts` or `Quick starts` to be consistent?

2024-03-19 09:52 UTC, dfennessy commented
> @dfennessy @lcavalle currently at the dashboard we have a button with string `Quickstarts` that redirect to Quickstarts page which has a header `Quick starts`. Could you please clarify if we should use `Quickstarts` or `Quick starts` to be consistent?

@lvillen It should be `Quick starts`

2024-03-20 13:05 UTC, jlledom commented on app/controllers/provider/sessions_controller.rb
> +      cookies[:first_login] = { value: 'true' } if current_user.user_sessions.empty?
IMO you don't need to use cookies, that's stored on the client and can be manipulated by the user. Specially when the cookie is not encrypted. If any, you should use the store session. However, I don't think you need the session neither. Here you could just store whether this is the first login:

```suggestion
      first = current_user.user_sessions.empty?
```

And then a couple lines below set the flash notice accordingly:

```ruby
flash[:notice] = first ? 'You can use quick starts to learn about 3scale features step by step. <a href="/p/admin/quickstarts">Take tour</a>'.html_safe : 'Signed in successfully'
```
Even better if you use i18n and load the text from `en.yml`

2024-03-20 13:05 UTC, jlledom commented on app/views/provider/admin/dashboards/show.html.slim
> +  a href="/p/admin/quickstarts" Quickstarts
I think this is too much and the flash notice should be enough, but if that's what they want...

2024-03-22 09:23 UTC, josemigallas requested changes

2024-03-22 09:23 UTC, josemigallas commented on app/views/provider/admin/dashboards/show.html.slim
> +  a href="/p/admin/quickstarts" Quickstarts
```suggestion
  a href=provider_admin_quickstarts_path Quickstarts
```

2024-03-22 09:23 UTC, josemigallas commented on test/integration/provider/admin/dashboards_controller_test.rb
> +  end
This is no integration test. I think it's enough with the cucumber.

2024-05-14 06:33 UTC, jlledom commented on app/controllers/provider/admin/dashboards_controller.rb
> +    flash[:quick_starts_notice] = t('provider.admin.dashboards.quick_starts_html', link: provider_admin_quickstarts_path).html_safe
In order to make it easier to understand that we are using one flash object to transfer data between controllers and the other to show the notice, I would call the objects `flash[:first_login]` and `flash[:notice]`

```suggestion
    return unless flash[:first_login]

    flash[:notice] = t('provider.admin.dashboards.quick_starts_html', link: provider_admin_quickstarts_path).html_safe
```

2024-05-14 15:15 UTC, jlledom approved these changes

2024-05-23 08:53 UTC, merged