🛂 Hide some menus from members
3scale/porta pull request #3886
Opened 2024-09-10 15:33 UTC by josemigallas

2024-09-11 08:26 UTC, jlledom reviewed
Why does this branch come from `bye_bye_webpacker`? couldn't this be done over `master` or `ruby-3.1`

Also, could you please add a description to the PR?

2024-09-11 08:26 UTC, jlledom commented on app/presenters/provider/admin/backend_apis_index_presenter.rb
> +  attr_reader :current_user, :pagination_params, :sorting_params, :search, :ability
I don't think `@current_user` and `@ability` should be publicly accessible unless that's really needed. Same for all other occurrences.

2024-10-15 08:29 UTC, jlledom requested changes
I tried this locally, these are my findings:

- https://issues.redhat.com/browse/THREESCALE-11237
  - Scenario:
    - Member with Access & query analytics
    - Two Products, two backends
    - The first product has two backends, the second product has no backends
  - Result
    - Giving it access to any product will show the dashboard tab for all backends
    - Giving it access to no product will hide the backend widget
    - In no case I can see only the backend widget with no product widget
    - This behaves exactly the same in master and in this PR
- https://issues.redhat.com/browse/THREESCALE-11357
  - Scenario:
    - Same permissions as in the issue ([check](https://issues.redhat.com/secure/attachment/13265014/member-user-permissions.png))
    - Two Products, two backends
    - The first product has two backends, the second product has no backends
  - Result
    - "Create" buttons appearing in the dashboard
      - I reproduced it in master, but can't reproduce it in this PR, so it's fixed 👍
    - Product -> Integration -> Backend can attempt to create a backend
        - I reproduced this in master but also in this PR, so it's not fixed
- Tests
  - I don't know whether we have tests for all the scenarios described in the Jira issues. I guess not, otherwise they would have failed. It would be good to add such tests

2025-01-07 17:27 UTC, jlledom commented on app/presenters/api/services_index_presenter.rb
> +    user.admin? || can?(:create, Service)
> Is this what we're looking for? https://github.com/3scale/porta/blob/3scale-2.15-stable/config/abilities/provider_admin.rb

Yes, that's it. So in this case, checking for `user.admin?` was wrong because there are situations where the user is admin but it can't create services. In those situations, the method should return `false` but it returns `true`. So removing `user.admin?` is the right thing to do.

2025-01-07 17:28 UTC, jlledom commented on app/presenters/provider/admin/dashboard_presenter.rb
> +    user.admin? || can?(:create, Service)
Yes, `user.admin?` must be removed

```suggestion
    can?(:create, Service)
```

2025-01-07 17:31 UTC, jlledom commented
From my previous comment:

>     * https://issues.redhat.com/browse/THREESCALE-11357
>       
>       * Scenario:
>         
>         * Same permissions as in the issue ([check](https://issues.redhat.com/secure/attachment/13265014/member-user-permissions.png))
>         * Two Products, two backends
>         * The first product has two backends, the second product has no backends
>       * Result
>         
>         * "Create" buttons appearing in the dashboard
>           
>           * I reproduced it in master, but can't reproduce it in this PR, so it's fixed 👍
>         * Product -> Integration -> Backend can attempt to create a backend
>           
>           * I reproduced this in master but also in this PR, so it's not fixed
> 

I tried this again and got the same results.

2025-01-08 11:59 UTC, josemigallas commented
UPDATES:


* Now "Access and query analytics" for backends only will hide the products widget in the dashboard:
<img width="1592" alt="Screenshot 2025-01-08 at 09 18 33" src="https://github.com/user-attachments/assets/97b2a5bf-7a14-4b08-a5e5-c289929114a6" />

* In Product > Integration > Backends, adding a backend now won't show an option to create a backend without permission:
![Screenshot 2025-01-08 at 12 58 38](https://github.com/user-attachments/assets/f631d242-fa39-42ff-bd01-ed0ed9113c47)

2025-01-09 10:20 UTC, jlledom commented
I tried this again:

>     * Now "Access and query analytics" for backends only will hide the products widget in the dashboard:

Works for me 👍

> 
>     * In Product > Integration > Backends, adding a backend now won't show an option to create a backend without permission:

This still fails for me:

- For a product with no backends, "Product > Integration > Backends" looks like this:

![image](https://github.com/user-attachments/assets/be88484f-1bf3-40c5-b8c7-cb4ac16de192)

There's an "Add a backend button", when clicking it, the screens to create backends auto-complete for existing backends:

![image](https://github.com/user-attachments/assets/19e96aa6-83fd-4580-80be-b1f3ce7d81b0)

And I can create the backend correctly.

I think it would be better to just not show the "Add a backend button" at all. Also, even if the screen loads and the existing backends are auto-completed, trying to create a backend should fail

2025-01-10 08:38 UTC, josemigallas commented
> This still fails for me:
> * For a product with no backends, "Product > Integration > Backends" looks like this:
> 
> ![image](https://private-user-images.githubusercontent.com/17052241/401495432-be88484f-1bf3-40c5-b8c7-cb4ac16de192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTg0NzQsIm5iZiI6MTczNjQ5ODE3NCwicGF0aCI6Ii8xNzA1MjI0MS80MDE0OTU0MzItYmU4ODQ4NGYtMWJmMy00MGM1LWI4YzctY2I0YWMxNmRlMTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDA4MzYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTcwNmIyMDAzNGFjNDZlZWM2OWMzOTU3MTA1OWE3ZjFmMzJlYzc0NjNhM2NjZWJkM2YxZjA2OTUwNWRjZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MEWBSv2zvfdCeHil8hZODnX4FMPOBXhoQfypXGZA0P0)
> There's an "Add a backend button", when clicking it, the screens to create backends auto-complete for existing backends:
> ![image](https://private-user-images.githubusercontent.com/17052241/401495845-19e96aa6-83fd-4580-80be-b1f3ce7d81b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTg0NzQsIm5iZiI6MTczNjQ5ODE3NCwicGF0aCI6Ii8xNzA1MjI0MS80MDE0OTU4NDUtMTllOTZhYTYtODNmZC00NTgwLTgwYmUtYjFmM2NlN2Q4MWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDA4MzYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MGVmZjJjZTcxYWU1NGUzZTZjOGMzZjY2YjQyNDQwYzdlN2UwZmU1NTlmZDE5MGI1MDY4NWRhNmE3NDU5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UnHsZeWFNVKwV6THqtQNcSsBfbms1j_7qXSK2BGxLCI)
> And I can create the backend correctly.
> I think it would be better to just not show the "Add a backend button" at all. Also, even if the screen loads and the existing backends are auto-completed, trying to create a backend should fail


@jlledom However, this is not creating a new backend. It is simply adding an existing backend to a product.

2025-01-10 11:24 UTC, jlledom commented
> @jlledom However, this is not creating a new backend. It is simply adding an existing backend to a product.

Is that supposed to be allowed? In that case, OK

2025-01-10 11:24 UTC, jlledom submitted a review, later dismissed

2025-01-13 09:28 UTC, josemigallas commented
UPDATE:

A member without access to a Product won't see it in its backend Overview page:
<img width="1728" alt="Screenshot 2025-01-13 at 10 27 53" src="https://github.com/user-attachments/assets/6f2369f2-704b-456b-8c23-e114a328ec89" />

2025-01-13 12:11 UTC, jlledom commented on features/provider/dashboard/widgets.feature
> +    Scenario: User does not have access to service admin sections
The last three scenarios share the same name

2025-01-14 15:57 UTC, mayorova commented on app/presenters/provider/admin/dashboard_presenter.rb
> +  # TODO: for some reason, accessible_backend_apis is not empty even though can?(:see, BackendApi) is false
I think this scope is just `BackendApi.where.not(state: DELETED_STATE)`, but I might be wrong...

2025-01-14 16:02 UTC, mayorova submitted a review, later dismissed
I didn't review the code itself carefully enough, but I think the behavior is now reasonable and fixes the three related JIRAs.

2025-01-15 08:41 UTC, josemigallas commented on app/presenters/provider/admin/dashboard_presenter.rb
> +  # TODO: for some reason, accessible_backend_apis is not empty even though can?(:see, BackendApi) is false
That makes sense

2025-01-15 09:22 UTC, merged